language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.4
  - 2.4.1
gemfile:
  - gemfiles/gemfile
  - gemfiles/fluentd.0.10.42.gemfile

script: "bundle exec rake spec"

branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/fluentd.0.10.42.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/fluentd.0.10.42.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/fluentd.0.10.42.gemfile
